# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  host: localhost
  adapter: mysql2
  database: awarder_development
  encoding: utf8
  username: root
  password:


test:
  host: localhost
  adapter: mysql2
  database: awarder_development
  encoding: utf8
  username: root
  password:

production:
  host: localhost
  adapter: mysql2
  database: awarder_development
  encoding: utf8
  username: root
  password:

